### ISSUE TITLE
Won't allow you to login if password contains an "&" symbol

### ISSUE THREAD

**Issue by SeanBannister** [meteor/windows-preview#112]
If your password contains an "&" symbol and you try to login using the Windows Meteor installer it throws the error "incorrect password entered" I've only tested the "&" symbol, I'm unsure if this is an issue with other ASCII characters.

**Comment by stubailo** [comment]
Confirmed!

**Comment by avital** [comment]
@SeanBannister, I believe that this has been fixed, could you verify by running the [latest installer](http://install.meteor.com/windows)?

**Comment by SeanBannister** [comment]
Thanks @avital, can confirm this is fixed.

**Comment by SeanBannister** [comment]
@avital Sorry my mistake accidentally tested with the @ symbol which works fine but passwords containing the & symbol are still not accepted.

**Comment by avital** [comment]
I just tried creating a user with password "foo&a" and successfully logged in with the installer.
