### ISSUE TITLE
Mongo shell is not opening on local DB server although app is running

### ISSUE THREAD

**Issue by funkybunky** [meteor/windows-preview#40]
Win7 Pro 64, running V 0.1.1
following the tutorial https://www.meteor.com/try/3 on step 3
opened a new cmd (tried also with elevated rights) and typed "meteor mongo" in the project dir
got "mongo: Meteor isn't running a local MongoDB server."
although I have the Meteor sample app running on the other cmd (as stated in the tutorial)

**Comment by esgy** [comment]
Tried that on my end also on w7 pro 64 and it worked fine.

**Comment by funkybunky** [comment]
just re-tried it with elevated cmd and freshly created sample project, error persists
FS is NTFS

**Comment by Slava** [comment]
Works fine for me, @funkybunky can you please provide more information on how you run the commands or record a video if it helps?

**Comment by funkybunky** [comment]
Hi! Do I have to put Mongo in the PATH first?
I just followed the steps provided in the tutorial: run the app locally through "meteor", open another cmd in the same dir and typed "meteor mongo"

**Comment by Slava** [comment]
No, you don't have to set PATH env variable. Your actions would look something like this:

    open cmd.exe
    cd C:\users\myuser\myapp
    meteor

   open another cmd.exe
   cd C:\users\myuser\myapp
   meteor mongo

**Comment by funkybunky** [comment]
well, that's exactly what I did ;-)
maybe we wait until another user reports the same problem? I don't want to waste your efforts, if it's just a strange behaviour on my machine. 
Is there another way I could try to access the database directly, perhaps in a GUI?

**Comment by tnedich** [comment]
I have the same problem Win7 Ultimate 64-bit.

**Comment by stubailo** [comment]
I think this is fixed in the latest release.

**Comment by tnedich** [comment]
No problem is still there Win7 Ultimate 64-bit. (windows preview v 0.1.6)

**Comment by SanthoshMR** [comment]
I'm running Win 8.1 64-bit and I've same issue. As funkybunky said, my meteor app is running and I still get the below error:
<pre>
mongo: Meteor isn't running a local MongoDB server.

This command only works while Meteor is running your application locally. Start your application first. (This error will also occur if you asked Meteor to use a
different MongoDB server with $MONGO_URL when you ran your application.)

If you're trying to connect to the database of an app you deployed with 'meteor deploy', specify your site's name with this command.
</pre>

**Comment by funkybunky** [comment]
Hi folks,
after the initial problems with Win, I installed Ubuntu, so I don't follow this issue anymore. just to let you know why I went quiet.. :)

**Comment by masaltzman** [comment]
I'm seeing the same thing on CentOS 7. 

$ cd simple-todos
$ meteor
[[[[[ ~/simple-todos ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3000/


=== then, in another terminal:

$ cd simple-todos
$ meteor mongo

mongo: Meteor isn't running a local MongoDB server.

This command only works while Meteor is running your application locally. Start
your application first. (This error will also occur if you asked Meteor to use
a different MongoDB server with $MONGO_URL when you ran your application.)

If you're trying to connect to the database of an app you deployed with
'meteor deploy', specify your site's name with this command.

**Comment by tnedich** [comment]
Yes it works that way, just not working when using **meteor mongo** inside meteor project. I just tried what @masaltzman suggested and it works.

**Comment by Slava** [comment]
@masaltzman I don't think your issue is related? You are on CentOS (which is a linux distro). Either the issue is different, or the issues is cross-platform.

**Comment by Slava** [comment]
Should be fixed in https://github.com/meteor/meteor/commit/155375da1f9281638ef6e9a340fecabdbc850a30

**Comment by hatsevich** [comment]
I had the same issue on Mac and I figured out that the problem was because the path to the app folder contained a folder named with Russian letters. After I moved the app to a folder with only-english-letters path the error disappeared.

**Comment by Slava** [comment]
Fixed in 1.1RC0

**Comment by tchiagoneses** [comment]
try as su:

sudo su

meteor mongo

it worked for me, i was getting the same error

**Comment by boustanihani** [comment]
@tchiagoneses ```**sudo** meteor mongo``` also solved my problem, but why ??? I did not start meteor with sudo, so why do we need sudo to access mongo ???

**Comment by boustanihani** [comment]
Another question, is there a way to specify which port the builtin mongodb should use?

**Comment by SibuStephen** [comment]
Why does the Mongo Versioning Issue occur ,  because as far as i know when i was trying the same while installing MEAN i got the same issue and while running meteor i got the same mongo Version(upgrade downgrade) issue occured as such.
